import { LitElement } from 'lit';
import { Button } from '@material/mwc-button';
import { Dialog } from '@material/mwc-dialog';
import { Fab } from '@material/mwc-fab';
import { Icon } from '@material/mwc-icon';
import { IconButton } from '@material/mwc-icon-button';
import { IconButtonToggle } from '@material/mwc-icon-button-toggle';
import { List } from '@material/mwc-list';
import { ListItem } from '@material/mwc-list/mwc-list-item.js';
import { Menu } from '@material/mwc-menu';
import { SldEditor } from './sld-editor.js';
declare const OscdEditorSld_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
export default class OscdEditorSld extends OscdEditorSld_base {
    static scopedElements: {
        'mwc-button': typeof Button;
        'mwc-dialog': typeof Dialog;
        'mwc-fab': typeof Fab;
        'mwc-icon': typeof Icon;
        'mwc-icon-button': typeof IconButton;
        'mwc-icon-button-toggle': typeof IconButtonToggle;
        'mwc-list': typeof List;
        'mwc-list-item': typeof ListItem;
        'mwc-menu': typeof Menu;
        'sld-editor': typeof SldEditor;
    };
    doc: XMLDocument;
    docVersion: number;
    gridSize: number;
    nsp: string;
    templateElements: Record<string, Element>;
    inAction: boolean;
    get showLabels(): boolean;
    get showIeds(): boolean;
    labelToggle?: IconButtonToggle;
    iedToggle?: IconButtonToggle;
    about?: Dialog;
    iedMenu?: Menu;
    sldEditor?: SldEditor;
    zoomIn(): void;
    zoomOut(): void;
    startPlacing(element: Element | undefined): void;
    reset(): void;
    handleKeydown: ({ key }: KeyboardEvent) => void;
    connectedCallback(): void;
    disconnectedCallback(): void;
    updated(changedProperties: Map<string, any>): void;
    convertSldAttributes(): void;
    render(): import("lit-html").TemplateResult<1>;
    insertOrGetIed(ied: Element, doc: XMLDocument): Element;
    insertSubstation(): void;
    static styles: import("lit").CSSResult;
}
export {};
