import { LitElement } from 'lit';
import type { Dialog } from '@material/mwc-dialog';
import type { IconButtonToggle } from '@material/mwc-icon-button-toggle';
import '@material/mwc-button';
import '@material/mwc-fab';
import '@material/mwc-icon-button';
import '@material/mwc-icon-button-toggle';
import '@material/mwc-icon';
import './sld-editor.js';
import { ConnectDetail, Point, StartConnectDetail } from './util.js';
export default class OscdEditorSld extends LitElement {
    doc: XMLDocument;
    get docVersion(): number;
    set docVersion(value: number);
    private _docVersion;
    gridSize: number;
    nsp: string;
    templateElements: Record<string, Element>;
    resizingBR?: Element;
    resizingTL?: Element;
    placing?: Element;
    placingOffset: Point;
    placingLabel?: Element;
    connecting?: {
        from: Element;
        path: Point[];
        fromTerminal: 'T1' | 'T2' | 'N1' | 'N2';
    };
    get showLabels(): boolean;
    labelToggle?: IconButtonToggle;
    about?: Dialog;
    zoomIn(): void;
    zoomOut(): void;
    startResizingBottomRight(element: Element | undefined): void;
    startResizingTopLeft(element: Element | undefined): void;
    startPlacing(element: Element | undefined, offset?: Point): void;
    startPlacingLabel(element: Element | undefined, offset?: Point): void;
    startConnecting(detail: StartConnectDetail): void;
    reset(): void;
    handleKeydown: ({ key }: KeyboardEvent) => void;
    connectedCallback(): void;
    disconnectedCallback(): void;
    updated(changedProperties: Map<string, any>): void;
    rotateElement(element: Element): void;
    placeLabel(element: Element, x: number, y: number): void;
    placeElement(element: Element, parent: Element, x: number, y: number): void;
    connectEquipment({ from, fromTerminal, to, toTerminal, path, }: ConnectDetail): void;
    render(): import("lit-html").TemplateResult<1>;
    insertSubstation(): void;
    static styles: import("lit").CSSResult;
}
