import { nothing, LitElement, TemplateResult } from 'lit';
import { Ref } from 'lit/directives/ref.js';
import type { Dialog } from '@material/mwc-dialog';
import type { TextField } from '@material/mwc-textfield';
import '@material/mwc-dialog';
import '@material/mwc-list';
import '@material/mwc-list/mwc-list-item.js';
import '@material/mwc-textfield';
import { Point } from './util.js';
type MenuItem = {
    handler: () => void;
    content: TemplateResult;
};
export declare class SLDEditor extends LitElement {
    doc: XMLDocument;
    substation: Element;
    editCount: number;
    gridSize: number;
    nsp: string;
    resizing?: Element;
    placing?: Element;
    placingLabel?: Element;
    connecting?: {
        equipment: Element;
        path: Point[];
        terminal: 'top' | 'bottom';
    };
    resizeSubstationUI: Dialog;
    substationWidthUI: TextField;
    substationHeightUI: TextField;
    sld: SVGGraphicsElement;
    mouseX: number;
    mouseY: number;
    mouseX2: number;
    mouseY2: number;
    menu?: {
        element: Element;
        top: number;
        left: number;
    };
    coordinatesRef: Ref<HTMLElement>;
    positionCoordinates(e: MouseEvent): void;
    openMenu(element: Element, e: MouseEvent): void;
    svgCoordinates(clientX: number, clientY: number): number[];
    canPlaceAt(element: Element, x: number, y: number, w: number, h: number): boolean;
    canResizeTo(element: Element, w: number, h: number): boolean;
    renderedLabelPosition(element: Element): Point;
    renderedPosition(element: Element): Point;
    handleKeydown: ({ key }: KeyboardEvent) => void;
    handleClick: (e: MouseEvent) => void;
    connectedCallback(): void;
    disconnectedCallback(): void;
    nearestOpenTerminal(equipment?: Element): 'top' | 'bottom' | undefined;
    groundTerminal(equipment: Element, name: 'T1' | 'T2'): void;
    flipElement(element: Element): void;
    equipmentMenuItems(equipment: Element): MenuItem[];
    busBarMenuItems(busBar: Element): MenuItem[];
    containerMenuItems(bayOrVL: Element): MenuItem[];
    renderMenu(): TemplateResult<1>;
    render(): TemplateResult<1>;
    renderLabel(element: Element): TemplateResult<2>;
    renderContainer(bayOrVL: Element, preview?: boolean): TemplateResult<2>;
    renderEquipment(equipment: Element, { preview, connect }?: {
        preview?: boolean | undefined;
        connect?: boolean | undefined;
    }): TemplateResult<2>;
    renderBusBar(busBar: Element): TemplateResult<2>;
    renderConnectivityNode(cNode: Element): TemplateResult<2> | typeof nothing;
    static styles: import("lit").CSSResult;
}
export {};
