import { TemplateResult } from 'lit';
export declare const resizePath: TemplateResult<2>;
export declare const movePath: TemplateResult<2>;
export declare const voltageLevelIcon: TemplateResult<1>;
export declare const voltageLevelGraphic: TemplateResult<1>;
export declare const bayIcon: TemplateResult<1>;
export declare const bayGraphic: TemplateResult<1>;
export declare const eqRingPath: TemplateResult<2>;
export declare function equipmentPath(equipmentType: string | null): TemplateResult<2>;
export declare function equipmentGraphic(equipmentType: string | null): TemplateResult<1>;
export declare function equipmentIcon(equipmentType: string): TemplateResult<1>;
export declare const connectivityNodeMarker: TemplateResult<2>;
export declare const groundedMarker: TemplateResult<2>;
export declare const powerTransformerTwoWindingSymbol: TemplateResult<2>;
export declare const symbols: TemplateResult<2>;
